# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-04 13:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoDataBuilder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='label')),
                ('desc_expression', models.TextField(help_text='an Expression... HELP', max_length=2000, verbose_name='expression description')),
                ('expression', models.TextField(help_text='an Expression... HELP', max_length=2000, verbose_name='expression')),
                ('casestudy_api_id', models.IntegerField(serialize=False, verbose_name='API Case Study ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, help_text='date when expression were last updated', verbose_name='last modified')),
                ('status', models.CharField(blank=True, max_length=128, null=True, verbose_name='status')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_geodatabuilder', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'ordering': ('label',),
                'verbose_name_plural': 'GeoDataBuilders',
            },
        ),
    ]
