# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-04 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geodatabuilder', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geodatabuilder',
            options={'ordering': ('label', 'created', 'updated'), 'verbose_name_plural': 'GeoDataBuilders'},
        ),
    ]
