# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-14 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodatabuilder', '0002_auto_20191104_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='geodatabuilder',
            name='expression_id_string',
            field=models.TextField(blank=True, help_text='an Expression... HELP', max_length=2000, verbose_name='expression id'),
        ),
    ]
