# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-19 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodatabuilder', '0004_auto_20191118_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='geodatabuilder',
            name='file',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='file'),
        ),
    ]
