# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-25 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodatabuilder', '0005_geodatabuilder_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geodatabuilder',
            name='file',
        ),
        migrations.AddField(
            model_name='geodatabuilder',
            name='file_path',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='file'),
        ),
    ]
