# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-22 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodatabuilder', '0006_auto_20191125_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geodatabuilder',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='date when expression were last updated', verbose_name='last modified'),
        ),
    ]
