# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-22 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodatabuilder', '0007_auto_20200622_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='geodatabuilder',
            name='file_updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='file data update'),
        ),
    ]
