# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-02-03 16:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolsR_1_8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default=None, max_length=255, verbose_name='label')),
                ('input_layers', models.TextField(help_text='an input layers... HELP', max_length=2000, verbose_name='layers')),
                ('input_criteria_distance_to_port', models.FloatField(default=0.2, verbose_name='distance to port')),
                ('input_criteria_optimal_growth', models.FloatField(default=0.4, verbose_name='optimal growth')),
                ('input_criteria_wave_heigth', models.FloatField(default=0.2, verbose_name='significant wave heigth')),
                ('input_criteria_fishing_effort', models.FloatField(default=0.2, verbose_name='fishing effort')),
                ('output_files', models.CharField(blank=True, max_length=255, verbose_name='path output files')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, help_text='date when expression were last updated', verbose_name='last modified')),
                ('public', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, max_length=128, null=True, verbose_name='status')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_tools_r', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'ordering': ('label', 'created', 'updated'),
                'verbose_name_plural': 'ToolsR 1.8',
            },
        ),
    ]
