# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-07 12:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tools_r', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolsR_1_11',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default=None, max_length=255, verbose_name='label')),
                ('input_layers', models.TextField(help_text='an input layers... HELP', max_length=2000, verbose_name='layers')),
                ('input_coast_line', models.CharField(max_length=255, verbose_name='coast line')),
                ('input_fishing_gear', models.CharField(max_length=255, verbose_name='path csv fisching gear')),
                ('input_components_cuts_grades', models.CharField(max_length=255, verbose_name='path csv components cuts grades')),
                ('input_extent', models.CharField(max_length=255, verbose_name='extent')),
                ('output_files', models.CharField(blank=True, max_length=255, verbose_name='path output files')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, help_text='date when expression were last updated', verbose_name='last modified')),
                ('public', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, max_length=128, null=True, verbose_name='status')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_tools_r_1_11', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'ordering': ('label', 'created', 'updated'),
                'verbose_name_plural': 'ToolsR 1.11',
            },
        ),
    ]
