# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-11 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools_r', '0002_toolsr_1_11'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolsr_1_8',
            name='input_criteria_distance_to_port',
        ),
        migrations.RemoveField(
            model_name='toolsr_1_8',
            name='input_criteria_fishing_effort',
        ),
        migrations.RemoveField(
            model_name='toolsr_1_8',
            name='input_criteria_optimal_growth',
        ),
        migrations.RemoveField(
            model_name='toolsr_1_8',
            name='input_criteria_wave_heigth',
        ),
    ]
