# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-11 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools_r', '0003_auto_20200211_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolsr_1_8',
            name='input_criteria',
            field=models.TextField(default=None, max_length=2000, verbose_name='criteria'),
        ),
    ]
