# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-13 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools_r', '0004_toolsr_1_8_input_criteria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolsr_1_11',
            name='input_coast_line',
        ),
        migrations.RemoveField(
            model_name='toolsr_1_11',
            name='input_components_cuts_grades',
        ),
        migrations.RemoveField(
            model_name='toolsr_1_11',
            name='input_extent',
        ),
        migrations.RemoveField(
            model_name='toolsr_1_11',
            name='input_fishing_gear',
        ),
        migrations.AddField(
            model_name='toolsr_1_11',
            name='input_criteria',
            field=models.TextField(default=None, max_length=2000, verbose_name='criteria'),
        ),
    ]
