# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-20 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools_r', '0005_auto_20200213_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolsr_1_11',
            name='pairwise_matrix',
            field=models.TextField(default=None, max_length=2000, verbose_name='pairwise matrix'),
        ),
    ]
