# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-21 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools_r', '0006_toolsr_1_11_pairwise_matrix'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolsr_1_11',
            name='fishing_gear',
            field=models.TextField(default=None, max_length=2000, verbose_name='fishing gear'),
        ),
    ]
