# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-24 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools_r', '0007_toolsr_1_11_fishing_gear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolsr_1_11',
            name='fishing_gear',
            field=models.TextField(default=None, max_length=9000, verbose_name='fishing gear'),
        ),
    ]
