# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-27 10:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tools_r', '0008_auto_20200224_0806'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolsR_1_12',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default=None, max_length=255, verbose_name='label')),
                ('input_layers', models.TextField(help_text='an input layers... HELP', max_length=2000, verbose_name='layers')),
                ('input_criteria', models.TextField(default=None, max_length=2000, verbose_name='criteria')),
                ('pairwise_matrix_ps', models.TextField(default=None, max_length=2000, verbose_name='pairwise matrix ps')),
                ('pairwise_matrix_tr', models.TextField(default=None, max_length=2000, verbose_name='pairwise matrix tr')),
                ('fishing_gear_ps', models.TextField(default=None, max_length=9000, verbose_name='fishing gear ps')),
                ('fishing_gear_tr1224', models.TextField(default=None, max_length=9000, verbose_name='fishing gear tr1224')),
                ('fishing_gear_tr2440', models.TextField(default=None, max_length=9000, verbose_name='fishing gear tr2440')),
                ('output_files', models.CharField(blank=True, max_length=255, verbose_name='path output files')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, help_text='date when expression were last updated', verbose_name='last modified')),
                ('public', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, max_length=128, null=True, verbose_name='status')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_tools_r_1_12', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'ordering': ('label', 'created', 'updated'),
                'verbose_name_plural': 'ToolsR 1.12',
            },
        ),
    ]
