# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-22 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools_r', '0009_toolsr_1_12'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolsr_1_8',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='date when expression were last updated', verbose_name='last modified'),
        ),
    ]
