# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-12-21 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools_r', '0010_auto_20200622_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolsr_1_11',
            name='type',
            field=models.IntegerField(default=2, verbose_name='type'),
        ),
        migrations.AddField(
            model_name='toolsr_1_12',
            name='type',
            field=models.IntegerField(default=2, verbose_name='type'),
        ),
        migrations.AddField(
            model_name='toolsr_1_8',
            name='type',
            field=models.IntegerField(default=2, verbose_name='type'),
        ),
    ]
