# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-11 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0028_auto_20190911_1731'),
        ('groups', '0027_auto_20180105_1631_squashed_0028_auto_20180606_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casestudies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_collections', to='groups.GroupProfile')),
                ('resources', models.ManyToManyField(related_name='resource_collections', to='base.ResourceBase')),
            ],
        ),
    ]
