# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-24 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasestudiesCsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Types',
            },
        ),
        migrations.CreateModel(
            name='CasestudiesModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Modules',
            },
        ),
        migrations.CreateModel(
            name='CasestudiesToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128, unique=True)),
                ('token', models.SlugField(max_length=128, unique=True)),
                ('schema', models.CharField(max_length=500)),
                ('is_enabled', models.BooleanField(default=False, help_text='Enabling this theme will disable the current enabled toke (if any)')),
            ],
            options={
                'verbose_name_plural': 'Token',
            },
        ),
        migrations.RemoveField(
            model_name='casestudies',
            name='group',
        ),
        migrations.RemoveField(
            model_name='casestudies',
            name='resources',
        ),
        migrations.DeleteModel(
            name='Casestudies',
        ),
    ]
