# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-12-05 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_ext', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainarea',
            name='identifier',
            field=models.CharField(max_length=255, unique=True, verbose_name='Domain Area name'),
        ),
    ]
